### ISSUE TITLE
Dog movement implemented based sheep and sheepfold position

### ISSUE THREAD

**Issue by ZanKorosak** [mh4043/CollectiveBehavour-GroupC#2]
Implement sheepdog driven algorithm explained in Algorithm 1 in related paper.

**Comment by vc4183** [comment]
Fixed with commit (85686dc12f6f9bdc008f755e9a58408a627b803c)
[Commit](https://github.com/mh4043/CollectiveBehavour-GroupC/commit/85686dc12f6f9bdc008f755e9a58408a627b803c)
